name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: [windows-2019]

    steps:
    - uses: actions/checkout@v1
      
    - name: "Pack and Push"
      shell: pwsh
      run: |
        #Install Choco
        Set-ExecutionPolicy Bypass -Scope Process -Force;
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        
        # Pack up
        choco pack
        
        # Set Key
        choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
        
        # Push
        choco push (Resolve-Path *.nupkg) --source https://push.chocolatey.org/
